[package]
name = "oracli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version = "0.11.14", features = ["blocking", "multipart"]}
regex = "1.7.1"
once_cell = "1.17.1"
